name: SLT
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
      - 'tensorflow==2.10.*'
      - tensorflow-datasets<4.9
      - pyaml==23.5.8
      - zstandard
      - numpy
      - pandas
      - scikit-learn==1.3.0
      - matplotlib
      - seaborn
      - scipy
      - pillow
      - h5py
      - tqdm
      - numba
      - joblib
      - PyQt5
      - pydantic
      - pytest
